# Generated by Django 4.1.1 on 2022-12-06 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_order_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='dish',
        ),
        migrations.AddField(
            model_name='order',
            name='dish',
            field=models.ManyToManyField(to='main.dish'),
        ),
    ]
